create table if not exists users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('Admin', 'Tester')),
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists projects (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text not null default 'A',
  color text not null default '#1d4ed8',
  status text not null default 'ACTIVE',
  documentation text not null default '',
  created_by bigint references users(id),
  updated_by bigint references users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists folders (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  name text not null,
  parent_id bigint references folders(id) on delete cascade,
  position integer not null default 0,
  created_by bigint references users(id),
  updated_by bigint references users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists test_cases (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  folder_id bigint references folders(id) on delete set null,
  title text not null,
  description text not null default '',
  steps text not null default '',
  expected_result text not null default '',
  position integer not null default 0,
  created_by bigint references users(id),
  updated_by bigint references users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists findings (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  test_case_id bigint references test_cases(id) on delete set null,
  title text not null,
  description text not null default '',
  status text not null check (status in ('Açık', 'Devam Ediyor', 'Çözüldü', 'Kapalı', 'Test Başarısız')),
  priority text check (priority in ('Düşük', 'Orta', 'Yüksek') or priority is null),
  configuration text not null default '',
  assigned_to bigint references users(id),
  created_by bigint references users(id),
  updated_by bigint references users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  finding_id bigint not null references findings(id) on delete cascade,
  body text not null,
  created_by bigint references users(id),
  created_at timestamptz not null default now()
);

create table if not exists session_logs (
  id bigint generated by default as identity primary key,
  finding_id bigint not null references findings(id) on delete cascade,
  body text not null,
  status text not null default 'Note',
  created_by bigint references users(id),
  updated_by bigint references users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists attachments (
  id bigint generated by default as identity primary key,
  finding_id bigint not null references findings(id) on delete cascade,
  log_id bigint references session_logs(id) on delete cascade,
  filename text not null,
  original_name text not null,
  mime_type text not null,
  size integer not null,
  url text not null,
  uploaded_by bigint references users(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_folders_parent on folders(parent_id);
create index if not exists idx_cases_folder on test_cases(folder_id);
create index if not exists idx_findings_case on findings(test_case_id);
create index if not exists idx_session_logs_finding on session_logs(finding_id);
